- platform: template
  switches:
    boiler:
      friendly_name: Boiler
      icon_template: mdi:shower
      value_template: "{{ is_state('sensor.boiler', 'ON') }}"
      turn_on:
        service: rest_command.boiler_turnon
      turn_off:
        service: rest_command.boiler_turnoff
    rm_heater:
      friendly_name: Room_Heater
      icon_template: mdi:shower
      value_template: "{{ is_state('sensor.rm_heater', 'ON') }}"
      turn_on:
        service: rest_command.rm_heater_turnon
      turn_off:
        service: rest_command.rm_heater_turnoff
#      plug_1:
#        local_ip_addr: !secret switcher_plug_1_ip
#        friendly_name: "Switcher Plug1"
#        scan_interval: 20
#        icon: mdi:water
#        phone_id: !secret switcher_phone_id
#        device_id: !secret switcher_plug_1_id
#        device_password: !secret switcher_plug_1_passwd
#      plug_2:
#        local_ip_addr: !secret switcher_plug_2_ip
#        friendly_name: "Mosquitto"
#        scan_interval: 20
#        icon: mdi:water
#        phone_id: !secret switcher_phone_id
#        device_id: !secret switcher_plug_2_id
#        device_password: !secret switcher_plug_2_passwd

