- id: 977082806f984ce28810e2e8ab5111bf
  alias: Morning
  trigger:
    platform: sun
    event: sunrise
    offset: 00:45:00
  action:
  - service: switch.turn_off
    entity_id: switch.ariel_lamp
  - delay:
      seconds: 5
  - service: switch.turn_off
    entity_id: switch.living_room_lamp
  - delay:
      milliseconds: 500
- id: f7a2d8b026634b8db2196c125bc1a426
  alias: Evening1
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  action:
  - entity_id: switch.living_room_lamp
    service: switch.turn_on
- id: lr_ac_changes
  alias: lr_ac_changes
  trigger:
  - platform: state
    entity_id: sensor.lr_ac_temp_sensor
  - platform: state
    entity_id: input_select.lr_ac_mode
  - platform: state
    entity_id: input_select.lr_ac_fan
  action:
  - condition: state
    entity_id: switch.lr_ac_state
    state: 'on'
  - service: script.tornado_ac_change_state
    data_template:
      selected_broadlink: remote.lr_broadlink_remote
- id: or_ac_changes
  alias: or_ac_changes
  trigger:
  - platform: state
    entity_id: sensor.or_ac_temp_sensor
  - platform: state
    entity_id: input_select.or_ac_mode
  - platform: state
    entity_id: input_select.or_ac_fan
  action:
  - condition: state
    entity_id: switch.or_ac_state
    state: 'on'
  - service: script.tornado_ac_change_state
    data_template:
      selected_broadlink: remote.or_broadlink_remote
- id: nr_ac_changes
  alias: nr_ac_changes
  trigger:
  - platform: state
    entity_id: sensor.nr_ac_temp_sensor
  - platform: state
    entity_id: input_select.nr_ac_mode
  - platform: state
    entity_id: input_select.nr_ac_fan
  action:
  - condition: state
    entity_id: switch.nr_ac_state
    state: 'on'
  - service: script.tornado_ac_change_state
    data_template:
      selected_broadlink: remote.ar_broadlink_remote
- id: duckdns_update
  alias: duckdns_update
  trigger:
  - minutes: /30
    platform: time_pattern
  action:
  - service: rest_command.duckdns_update
- id: qbt_pause
  alias: qbt_pause
  trigger:
  - hours: /2
    platform: time_pattern
  action:
  - service: shell_command.qbt_auto_pause
- id: '1648492140847'
  alias: talaviad
  description: Update Tal and Aviad dates
  trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: '23:00'
  condition: []
  action:
  - service: python_script.talnaviad_dates
  mode: single
