# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  login_attempts_threshold: 3
  #  ssl_certificate: !secret ssl_cert
  #  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.17.0.0/16

logger:
  default: warning
  logs:
  #   homeassistant.components.shell_command: debug
    homeassistant.components.rest_command: debug
  #   homeassistant.components.python_script: debug
  #   homeassistant.components.remote: debug
  #   homeassistant.components.script: debug
  #   homeassistant.components.switch: debug
  #   homeassistant.components.input_select: debug
  #   homeassistant.components.input_boolean: debug
  #   homeassistant.components.input_text: debug
  #   homeassistant.components.cover: debug
  #   homeassistant.components.sensor: debug
  #   homeassistant.components.group: debug
  #   homeassistant.components.automation: debug

python_script:

binary_sensor:
  - platform: ping
    host: 8.8.8.8
    count: 4
    scan_interval: 60
    name: Ping Google DNS
  - platform: ping
    host: !secret gw_ip
    count: 4
    scan_interval: 60
    name: Ping FW
  - platform: mqtt
    state_topic: "shellies/shellyht-F391D8/online"
    name: Shelly1 State
    payload_on: "true"
    payload_off: "false"
  - platform: mqtt
    state_topic: "shellies/shellyht-F03BCC/online"
    name: Shelly2 State
    payload_on: "true"
    payload_off: "false"

# camera:
#  - platform: ffmpeg
#    name: Camera C200 rtsp
#    input: !secret tapo_host
#  - platform: generic
#    name: rpi_cam
#    still_image_url: !secret pi_cam_url
#    verify_ssl: false

upnp:

# Text to speech

homekit:
  - filter:
      include_entities:
        - binary_sensor.0x00158d0003d0c033_contact
        - input_select.br_ac_mode
        - input_select.lr_ac_mode
        - input_select.nr_ac_mode
        - input_select.or_ac_mode
        - input_select.room_heater_timer_select
        - input_select.watter_heater_timer_select
        # - media_player.living_room_tv
        - switch.boiler
        - switch.rm_heater
        - script.good_night
        - sensor.shelly1_humidity
        - sensor.shelly1_temperature
        - sensor.shelly2_humidity
        - sensor.shelly2_humidity
        - sensor.shelly2_temperature
        - sensor.shelly2_temperature
        - switch.alice_bed_light
        - switch.ariels_room
        - switch.bathroom
        - switch.bedroom_ac
        - switch.br_ac_state
        - switch.kitchen1
        - switch.kitchen2
        - switch.living_room_lamp
        - switch.lr_ac_state
        - switch.lr_entry_light
        - switch.lr_light1
        - switch.lr_light2
        - switch.nr_ac_state
        - switch.office_light
        - switch.or_ac_state
        - switch.pantry
        - switch.room_heater
        - switch.toilet
        - switch.val_bed_light
        - switch.washer_light
        - switch.watter_heater
        # - vacuum.xiaomi_vacuum_cleaner

tts:
  - platform: google_translate

lovelace:
  mode: yaml

mqtt:
  broker: localhost
  username: homeassistant
  password: !secret mqtt_passwd
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: "hass/status"
    payload: "online"
  will_message:
    topic: "hass/status"
    payload: "offline"

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip
    token: !secret vacuum_token

shell_command:
  turn_off_lr_pc: !secret shell_cmd
  qbt_auto_pause: !secret qbt_auto_pause

webostv:
  host: !secret tv_ip
  name: Living Room TV
  turn_on_action:
    service: remote.send_command
    data:
      entity_id: remote.lr_broadlink_remote
      command: "b64: JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU="
  customize:
    sources:
      - netflix
      - HDMI 1
      - Plex

rest_command:
  duckdns_update:
    url: !secret duckdns_url
  boiler_turnon:
    url: !secret boiler_on_url
    method: POST
    payload: '{"minutes": {{states(''input_select.watter_heater_timer_select'')}}}'
    content_type: "application/json"
  boiler_turnoff:
    url: !secret boiler_off_url
    method: POST
  rm_heater_turnon:
    url: !secret rm_heater_on_url
    method: POST
    payload: '{ "minutes": {{states(''input_select.room_heater_timer_select'')}}}'
    content_type: "application/json"
  rm_heater_turnoff:
    url: !secret rm_heater_off_url
    method: POST

switch:
  !include_dir_merge_list switches/
  #media_player: !include media_players.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_text: !include input_text.yaml
sensor: !include sensors.yaml
cover: !include covers.yaml
group:
  !include groups.yaml
  # cloud: !include cloud.yaml
google_assistant: !include google_assistant.yaml
automation: !include automations.yaml
script:
  !include_dir_merge_named scripts/
  #script: !include scripts.yaml
homeassistant:
  customize: !include customize.yaml
