- platform: template
  covers:
    lr_ac_temp_cover:
      position_template: "{% if states.sensor.lr_ac_temp_sensor ==  none %}25{% else %}{{ states.sensor.lr_ac_temp_sensor.state | int }}{% endif %}"
      open_cover:
        service: input_text.set_value
        data_template:
          entity_id: input_text.lr_ac_temp_text
          value: "{{ [((states.input_text.lr_ac_temp_text.state | int) + 1), 30] | min }}"
      close_cover:
        service: input_text.set_value
        data_template:
          entity_id: input_text.lr_ac_temp_text
          value: "{{ [((states.input_text.lr_ac_temp_text.state | int) - 1), 16] | max }}"

    # Office ac cover
    or_ac_temp_cover:
      position_template: "{% if states.sensor.or_ac_temp_sensor ==  none %}25{% else %}{{ states.sensor.or_ac_temp_sensor.state | int }}{% endif %}"
      open_cover:
        service: input_text.set_value
        data_template:
          entity_id: input_text.or_ac_temp_text
          value: "{{ [((states.input_text.or_ac_temp_text.state | int) + 1), 30] | min }}"
      close_cover:
        service: input_text.set_value
        data_template:
          entity_id: input_text.or_ac_temp_text
          value: "{{ [((states.input_text.or_ac_temp_text.state | int) - 1), 16] | max }}"

    # Nursery ac cover
    nr_ac_temp_cover:
      position_template: "{% if states.sensor.nr_ac_temp_sensor ==  none %}25{% else %}{{ states.sensor.nr_ac_temp_sensor.state | int }}{% endif %}"
      open_cover:
        service: input_text.set_value
        data_template:
          entity_id: input_text.nr_ac_temp_text
          value: "{{ [((states.input_text.nr_ac_temp_text.state | int) + 1), 30] | min }}"
      close_cover:
        service: input_text.set_value
        data_template:
          entity_id: input_text.nr_ac_temp_text
          value: "{{ [((states.input_text.nr_ac_temp_text.state | int) - 1), 16] | max }}"
    # Bedroom ac cover
    br_ac_temp_cover:
      position_template: "{% if states.sensor.br_ac_temp_sensor ==  none %}25{% else %}{{ states.sensor.br_ac_temp_sensor.state | int }}{% endif %}"
      open_cover:
        service: input_text.set_value
        data_template:
          entity_id: input_text.br_ac_temp_text
          value: "{{ [((states.input_text.br_ac_temp_text.state | int) + 1), 30] | min }}"
      close_cover:
        service: input_text.set_value
        data_template:
          entity_id: input_text.br_ac_temp_text
          value: "{{ [((states.input_text.br_ac_temp_text.state | int) - 1), 16] | max }}"
