- platform: webostv
  host: !secret tv_ip
  name: lr_tv
  friendly_name: "Living Room TV"
  timeout: 5
  turn_on_action:
    service: remote.send_command
    data:
      entity_id: remote.lr_broadlink_remote
      command: b64:JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU=
  customize:
    sources:
      - netflix
      - HDMI 1
      - Plex
