- platform: template
  sensors:
    lr_ac_temp_sensor:
      value_template: "{{ states.input_text.lr_ac_temp_text.state }}"
    or_ac_temp_sensor:
      value_template: "{{ states.input_text.or_ac_temp_text.state }}"
    nr_ac_temp_sensor:
      value_template: "{{ states.input_text.nr_ac_temp_text.state }}"
    br_ac_temp_sensor:
      value_template: "{{ states.input_text.br_ac_temp_text.state }}"


- platform: season

#- platform: successful_logins
#  provider: 'extreme'

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /home
  - type: memory_use_percent
  - type: last_boot
  - type: processor_use
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: throughput_network_in
    arg: eth0
  - type: throughput_network_out
    arg: eth0

- platform: template
  sensors:
    ping_google_average:
      value_template: "{{ state_attr('binary_sensor.ping_google_dns', 'round_trip_time_avg') }}"
      unit_of_measurement: ms
    ping_fw_average:
      value_template: "{{ state_attr('binary_sensor.ping_fw', 'round_trip_time_avg') }}"
      unit_of_measurement: ms
    # watter_heater_watts: 
    #   friendly_name: Boiler Usage Watt
    #   unit_of_measurement: 'W'
    #   value_template: >
    #     {% if state_attr('switch.watter_heater', 'current_power_watts') %} {{ state_attr('switch.watter_heater', 'current_power_watts') }}
    #     {% else %} 0
    #     {% endif %}
    # watter_heater_amps:
    #   friendly_name: Boiler Usage Amp
    #   unit_of_measurement: 'A'
    #   value_template: >
    #     {% if state_attr('switch.watter_heater', 'current_power_amps') %} {{ state_attr('switch.watter_heater', 'current_power_amps') }}
    #     {% else %} 0
    #     {% endif %}
    # room_heater_watts:
    #   friendly_name: Bathroom Heater usage Watt
    #   unit_of_measurement: 'W'
    #   value_template: >
    #     {% if state_attr('switch.room_heater', 'current_power_watts') %} {{ state_attr('switch.room_heater', 'current_power_watts') }}
    #     {% else %} 0
    #     {% endif %}
    # room_heater_amps:
    #   friendly_name: Bathroom Heater usage Amp
    #   unit_of_measurement: 'A'
    #   value_template: >
    #     {% if state_attr('switch.room_heater', 'current_power_amps') %} {{ state_attr('switch.room_heater', 'current_power_amps') }}
    #     {% else %} 0
    #     {% endif %}

- platform: mqtt
  name: Shelly1 Humidity
  state_topic: "shellies/shellyht-F391D8/sensor/humidity"
  unit_of_measurement: "%"
- platform: mqtt
  name: Shelly1 Temperature
  state_topic: "shellies/shellyht-F391D8/sensor/temperature"
  unit_of_measurement: "°C"
- platform: mqtt
  name: Shelly1 Battery
  state_topic: "shellies/shellyht-F391D8/sensor/battery"
  unit_of_measurement: "%"

- platform: mqtt
  name: Shelly2 Humidity
  state_topic: "shellies/shellyht-F03BCC/sensor/humidity"
  unit_of_measurement: "%"
- platform: mqtt
  name: Shelly2 Temperature
  state_topic: "shellies/shellyht-F03BCC/sensor/temperature"
  unit_of_measurement: "°C"
- platform: mqtt
  name: Shelly2 Battery
  state_topic: "shellies/shellyht-F03BCC/sensor/battery"
  unit_of_measurement: "%"

- platform: qbittorrent
  url: !secret torrent_url
  username: !secret torrent_uid
  password: !secret torrent_pass

- platform: rest
  name: Boiler
  json_attributes:
    - state
    - time_left
    - time_on
    - auto_shutdown
    - power_consumption
    - electric_current
  resource: !secret boiler_url
  value_template: "OK"
- platform: template
  sensors:
    boiler_power:
      friendly_name: "boiler_power"
      unit_of_measurement: kW
      value_template: "{{ state_attr('sensor.Boiler', 'power_consumption') }}"
    boiler_amp:
      friendly_name: "boiler_amp"
      unit_of_measurement: A
      value_template: "{{ state_attr('sensor.Boiler', 'electric_current') }}"
    boiler_on_time:
      friendly_name: "boiler_on_time"
      value_template: "{{ state_attr('sensor.Boiler', 'time_on') }}"
    boiler_status:
      friendly_name: "boiler_state"
      value_template:  >-
        {% if state_attr('sensor.boiler', 'state') == 'ON' %}
          on
        {% else %}
          off
        {% endif %}

- platform: rest
  name: rm_heater
  json_attributes:
    - state
    - time_left
    - time_on
    - auto_shutdown
    - power_consumption
    - electric_current
  resource: !secret rm_heater_url
  value_template: "OK"
- platform: template
  sensors:
    rm_heater_power:
      friendly_name: "Heater_power"
      unit_of_measurement: kW
      value_template: "{{ state_attr('sensor.rm_heater', 'power_consumption') }}"
    rm_heater_amp:
      friendly_name: "Heater_amp"
      unit_of_measurement: A
      value_template: "{{ state_attr('sensor.rm_heater', 'electric_current') }}"
    rm_heater_on_time:
      friendly_name: "Heater_on_time"
      value_template: "{{ state_attr('sensor.rm_heater', 'time_on') }}"
    rm_heater_status:
      friendly_name: "heater_state"
      value_template:  >-
        {% if state_attr('sensor.rm_heater', 'state') == 'ON' %}
          on
        {% else %}
          off
        {% endif %}

